// @vitest-environment node

import { describe, expect, it } from 'vitest'

import {
  createPermissionRequest,
  createWorkspaceContext,
  type AgentAdapter,
  type AgentPlanInput,
  type ExecutionEvent,
  type TaskPlan
} from '@mango/core'

import {
  currentDesktopSchemaVersion,
  defaultDesktopSettings,
  type DesktopStateStore,
  type PersistedDesktopState
} from '../persistence/fileDesktopStore'
import { DesktopController } from './desktopController'

class MemoryDesktopStore implements DesktopStateStore {
  public constructor(public state: PersistedDesktopState | null) {}

  public async read(): Promise<PersistedDesktopState | null> {
    return this.state
  }

  public async write(state: PersistedDesktopState): Promise<void> {
    this.state = state
  }
}

class FakeAdapter implements AgentAdapter {
  public constructor(
    public readonly id: string,
    public readonly label: string,
    private readonly executionMode: 'success' | 'failure' = 'success'
  ) {}

  public async detectAvailability() {
    return {
      available: true,
      command: this.id,
      details: `${this.label} is ready`
    }
  }

  public async generatePlan(): Promise<TaskPlan> {
    return {
      headline: `${this.label} plan`,
      summary: `Plan generated by ${this.label}.`,
      steps: ['Inspect workspace', 'Generate plan', 'Execute task'],
      requestedPermissions: [
        createPermissionRequest('shell', `Run ${this.label}`),
        createPermissionRequest('filesystem', 'Update repository files')
      ]
    }
  }

  public async runApprovedPlan(input: AgentPlanInput): Promise<ExecutionEvent[]> {
    if (this.executionMode === 'failure') {
      throw new Error(`${this.label} failed for ${input.sessionId}`)
    }

    return [
      {
        type: 'terminal.output',
        id: `${input.sessionId}-${this.id}-evt-1`,
        level: 'info',
        message: `${this.label} executed the approved task`,
        createdAt: '2026-03-25T00:00:00.000Z'
      },
      {
        type: 'summary.ready',
        id: `${input.sessionId}-${this.id}-evt-2`,
        level: 'info',
        message: `${this.label} summary ready`,
        summary: `${this.label} finished the approved task.`,
        createdAt: '2026-03-25T00:00:01.000Z'
      }
    ]
  }
}

const workspace = createWorkspaceContext({
  id: 'workspace-main',
  name: 'Mango',
  rootPath: process.cwd(),
  shell: 'powershell',
  gitBranch: 'codex/mango-v1',
  gitStatusSummary: 'clean'
})

const createPersistedState = (): PersistedDesktopState => ({
  schemaVersion: currentDesktopSchemaVersion,
  activeTask: null,
  history: [],
  selectedWorkspaceId: workspace.id,
  settings: defaultDesktopSettings,
  workspaces: [workspace]
})

describe('DesktopController', () => {
  it('uses the requested adapter and persists it as the workspace primary adapter', async () => {
    const store = new MemoryDesktopStore(createPersistedState())
    const controller = new DesktopController(store, [
      new FakeAdapter('claude-code', 'Claude Code CLI'),
      new FakeAdapter('mock-claude', 'Mock Claude CLI')
    ])

    const nextState = await controller.generatePlan({
      prompt: 'Implement adapter registry',
      workspaceId: workspace.id,
      adapterId: 'claude-code'
    })

    expect(nextState.activeTask?.adapterId).toBe('claude-code')
    expect(nextState.activeTask?.plan?.headline).toBe('Claude Code CLI plan')
    expect(
      nextState.workspaces.find((entry) => entry.id === workspace.id)?.providerConfig
        ?.primaryAdapterId
    ).toBe('claude-code')
    expect(
      nextState.workspaces.find((entry) => entry.id === workspace.id)?.providerConfig
        ?.configuredAdapters
    ).toContain('claude-code')
  })

  it('marks the task as failed when the selected adapter crashes during execution', async () => {
    const store = new MemoryDesktopStore(createPersistedState())
    const controller = new DesktopController(store, [
      new FakeAdapter('claude-code', 'Claude Code CLI', 'failure'),
      new FakeAdapter('mock-claude', 'Mock Claude CLI')
    ])

    await controller.generatePlan({
      prompt: 'Implement adapter registry',
      workspaceId: workspace.id,
      adapterId: 'claude-code'
    })

    const nextState = await controller.approveAndRun()

    expect(nextState.activeTask?.adapterId).toBe('claude-code')
    expect(nextState.activeTask?.status).toBe('failed')
    expect(nextState.activeTask?.executionSummary).toContain('Claude Code CLI failed')
    expect(nextState.activeTask?.events.at(-1)).toMatchObject({
      type: 'terminal.output',
      level: 'error'
    })
  })

  it('treats approve and run as a no-op once the active task has already finished', async () => {
    const store = new MemoryDesktopStore(createPersistedState())
    const controller = new DesktopController(store, [
      new FakeAdapter('claude-code', 'Claude Code CLI'),
      new FakeAdapter('mock-claude', 'Mock Claude CLI')
    ])

    await controller.generatePlan({
      prompt: 'Implement adapter registry',
      workspaceId: workspace.id,
      adapterId: 'claude-code'
    })

    const completedState = await controller.approveAndRun()
    const repeatedState = await controller.approveAndRun()

    expect(completedState.activeTask?.status).toBe('succeeded')
    expect(repeatedState.activeTask?.status).toBe('succeeded')
    expect(repeatedState.activeTask?.events).toHaveLength(
      completedState.activeTask?.events.length ?? 0
    )
    expect(repeatedState.activeTask?.executionSummary).toBe(
      completedState.activeTask?.executionSummary
    )
  })
})
